export const data = {
  products: [
    {
      _id: "1",
      name: "Google pixel 6Pro",
      category: "Phones",
      image: "/images/product-1.jpg",
      price: 300000,
      brand: "Google",
      countInStock: 20,
      rating: 5,
      numReviews: 10,
      description: "flagship made by google",
    },
    {
      _id: "2",
      name: "Google pixel 6Pro",
      category: "Phones",
      image: "/images/product-1.jpg",
      price: 92000,
      brand: "Google",
      countInStock: 20,
      rating: 5,
      numReviews: 10,
      description: "flagship made by google",
    },
    {
      _id: "3",
      name: "Pro",
      category: "Phones",
      image: "/images/product-1.jpg",
      price: 9876,
      brand: "Google",
      countInStock: 20,
      rating: 5,
      numReviews: 10,
      description: "flagship made by google",
    },
    {
      _id: "4",
      name: "6Pro",
      category: "Phones",
      image: "/images/product-1.jpg",
      price: 300000,
      brand: "Google",
      countInStock: 20,
      rating: 5,
      numReviews: 10,
      description: "flagship made by google",
    },
    {
      _id: "5",
      name: "Google pixel 6Pro",
      category: "Phones",
      image: "/images/product-1.jpg",
      price: 3570000,
      brand: "Google",
      countInStock: 20,
      rating: 5,
      numReviews: 10,
      description: "flagship made by google",
    },
    {
      _id: "6",
      name: " pixel 6Pro",
      category: "Phones",
      image: "/images/product-1.jpg",
      price: 6477,
      brand: "Apple",
      countInStock: 20,
      rating: 3,
      numReviews: 10,
      description: "flagship made by Apple",
    },
    {
      _id: "7",
      name: "Marvel Pro",
      category: "Phones",
      image: "/images/product-1.jpg",
      price: 6477,
      brand: "Marvel",
      countInStock: 20,
      rating: 3,
      numReviews: 10,
      description: "flagship made by Marvel",
    },
    {
      _id: "8",
      name: "Marvel 2Pro",
      category: "Phones",
      image: "/images/product-1.jpg",
      price: 6477,
      brand: "Marvel",
      countInStock: 20,
      rating: 3,
      numReviews: 10,
      description: "flagship made by Marvel",
    },
    {
      _id: "9",
      name: "Marvel 2Pro",
      category: "Phones",
      image: "/images/product-1.jpg",
      price: 6477,
      brand: "Marvel",
      countInStock: 20,
      rating: 3,
      numReviews: 10,
      description: "flagship made by Marvel",
    },
  ],
};
